
# UN Immigration Data Transformation

**Course:** AIT620 – Methods of Artificial Intelligence and Machine Learning

## Introduction

In this assignment, I will use Python and pandas to clean and transform the United Nations immigration dataset for Canada.

The dataset contains immigration records from 1980 to 2013.

## Objectives

1. Load the Excel dataset into a pandas DataFrame.
2. Remove unnecessary rows and columns.
3. Rename columns for better readability.
4. Clean missing values.
5. Calculate total immigration for each country.
6. Display the final DataFrame in the required format.

In [1]:

# Install openpyxl in the current Jupyter Python environment
%pip install openpyxl

Requirement already satisfied: openpyxl in /opt/anaconda3/envs/my_env/lib/python3.14/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/anaconda3/envs/my_env/lib/python3.14/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:

# Step 2: Check Excel file and worksheet names

import pandas as pd
from pathlib import Path

# Find Excel files in the current folder
excel_files = list(Path(".").glob("*.xlsx"))

# Display available Excel files
print("Excel files found:")
for file in excel_files:
    print(file.name)

# Display worksheet names
if excel_files:
    excel_file = pd.ExcelFile(excel_files[0])
    print("\nAvailable worksheets:")
    print(excel_file.sheet_names)
else:
    print("No Excel file found.")

Excel files found:
Canada.xlsx

Available worksheets:
['Regions by Citizenship', 'Canada by Citizenship']

In [3]:

# Step 3: Load the UN Immigration Dataset

# Read the Canada by Citizenship worksheet
# Skip the first 20 rows containing titles and headers
# Use the next row as the column headers
df = pd.read_excel(
    "Canada.xlsx",
    sheet_name="Canada by Citizenship",
    skiprows=20
)

# Display the dataset dimensions
print("Dataset Shape:", df.shape)

# Display column names
print("\nColumn Names:")
print(df.columns.tolist())

# Display the first five rows
print("\nFirst Five Rows:")
display(df.head())

Dataset Shape: (197, 43)

Column Names:
['Type', 'Coverage', 'OdName', 'AREA', 'AreaName', 'REG', 'RegName', 'DEV', 'DevName', 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013]

First Five Rows:

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1

In [4]:

# Step 4: Remove Unnecessary Columns

# Create a copy to preserve the original dataset
df_clean = df.copy()

# Define columns that are not needed
columns_to_remove = [
    "Type",
    "Coverage",
    "AREA",
    "REG",
    "DEV"
]

# Remove unnecessary columns
df_clean = df_clean.drop(columns=columns_to_remove)

# Display the updated dataset dimensions
print("Updated Dataset Shape:", df_clean.shape)

# Display the remaining column names
print("\nRemaining Columns:")
print(df_clean.columns.tolist())

# Display the first five rows
display(df_clean.head())

Updated Dataset Shape: (197, 38)

Remaining Columns:
['OdName', 'AreaName', 'RegName', 'DevName', 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013]

,OdName,AreaName,RegName,DevName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1450,1223,856,702,560,716,561,539,620,603
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,1,1

In [5]:

# Step 5: Rename Columns

# Rename columns to make the dataset easier to understand
df_clean = df_clean.rename(columns={
    "OdName": "Country",
    "AreaName": "Continent",
    "RegName": "Region"
})

# Display updated column names
print("Updated Column Names:")
print(df_clean.columns.tolist())

# Display the first five rows
display(df_clean.head())

Updated Column Names:
['Country', 'Continent', 'Region', 'DevName', 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013]

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1450,1223,856,702,560,716,561,539,620,603
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,0,1,1,0,0,0,0,1,1

In [6]:

# Step 6: Set Country as the DataFrame Index

# Use country names instead of row numbers
df_clean = df_clean.set_index("Country")

# Display the index name
print("Index Name:", df_clean.index.name)

# Display the updated dataset shape
print("Dataset Shape:", df_clean.shape)

# Display the first five rows
display(df_clean.head())

Index Name: Country
Dataset Shape: (197, 37)

,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,1986,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,496,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,1,...,1450,1223,856,702,560,716,561,539,620,603
Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,69,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,2,...,0,0,1,1,0,0,0,0,1,1

In [7]:

# Step 7: Calculate Total Immigration by Country

# Create a list of years from 1980 to 2013
years = list(range(1980, 2014))

# Convert immigration values to numeric format
# Replace missing or invalid values with zero
df_clean[years] = df_clean[years].apply(
    pd.to_numeric, errors="coerce"
).fillna(0)

# Calculate total immigration for each country
df_clean["Total"] = df_clean[years].sum(axis=1).astype(int)

# Display the first five countries and their totals
display(df_clean[["Continent", "Region", "DevName", "Total"]].head())

# Display the final dataset shape
print("Dataset Shape:", df_clean.shape)

               Continent           Region             DevName  Total
Country
Afghanistan         Asia    Southern Asia  Developing regions  58639
Albania           Europe  Southern Europe   Developed regions  15699
Algeria           Africa  Northern Africa  Developing regions  69439
American Samoa   Oceania        Polynesia  Developing regions      6
Andorra           Europe  Southern Europe   Developed regions     15

Dataset Shape: (197, 38)

In [8]:

# Step 8: Validate and Display the Final DataFrame

# Define the required column order
final_columns = ["Continent", "Region", "DevName"] + years + ["Total"]

# Arrange the columns in the required order
df_final = df_clean[final_columns].copy()

# Display the final transformed dataset
print("Final Dataset Shape:", df_final.shape)
print("Index Name:", df_final.index.name)

display(df_final.head())

# Verify that the total matches the sum of yearly values
totals_match = (
    df_final[years].sum(axis=1) == df_final["Total"]
).all()

print("All immigration totals are correct:", totals_match)

Final Dataset Shape: (197, 38)
Index Name: Country

,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,1986,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Country,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,496,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,1,...,1223,856,702,560,716,561,539,620,603,15699
Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,69,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,2,...,0,1,1,0,0,0,0,1,1,15

All immigration totals are correct: True


## Conclusion

In this assignment, I used Python and pandas to clean and transform the United Nations immigration dataset for Canada.

I completed the following tasks:

1. Loaded the Excel dataset into a pandas DataFrame.
2. Removed unnecessary columns.
3. Renamed columns to improve readability.
4. Set Country as the DataFrame index.
5. Converted immigration data into numeric values.
6. Calculated total immigration for each country from 1980 to 2013.
7. Verified that all calculated totals were correct.

### Final Results

The final dataset contains 197 countries and 38 columns, including the Total column.

The validation confirmed that all immigration totals were calculated correctly.

This assignment helped me understand how to use pandas for data cleaning, transformation, and validation.

## Data Source

United Nations, Department of Economic and Social Affairs, Population Division. (2015). *International migration flows to and from selected countries: The 2015 revision*.